name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["2.7", "3.6", "3.7", "3.8"]
        plone_version: ["5.2"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install Plone dependencies
      run: python -m pip install -r https://dist.plone.org/release/${{ matrix.plone_version }}-latest/requirements.txt
    - name: Cache eggs
      uses: actions/cache@v2
      with:
        path: eggs
        key: eggs-${{ hashFiles('**/*.cfg') }}
        restore-keys: eggs-
    - name: Run buildout to install bin/test
      run: buildout -Nv install test
    - name: Run the tests
      run: ./bin/test
